#!/usr/bin/env python3
"""
E1-R Phase 3H Market Flow / Capital Momentum Confirmation Diagnostic

Diagnostic only. Does not modify trading logic, orders, exports/backtest.json,
or any strategy implementation.

Purpose:
Validate whether SIDEWAYS / DOWNTREND smooth-trend candidates improve when the
smooth price trend is backed by real market participation:
- relative volume
- up-day volume ratio
- dollar volume / liquidity
- price-volume confirmation
- setup quality proxies such as volume dry-up, volatility compression, and 52-week-high proximity

This script deliberately protects the existing UPTREND Confirmed execution path.
It only evaluates non-UPTREND candidates generated by Phase 3G STC logic.

Expected inputs after `python3 run_backtest.py`:
- exports/backtest.json, containing E1_AUDITED_G4_MINHOLD10 and E1R_REGIME_AWARE_V0_1
- data/prices/*.json with close and preferably volume fields
- scripts/e1r_phase3g_smooth_trend_confirmation_diagnostic.py
- data/research/e1r/e1r_phase3g_smooth_trend_confirmation_diagnostic.json
- data/research/e1_5y/regimes/spx_regime_daily.json

Outputs:
- data/research/e1r/e1r_phase3h_market_flow_confirmation_diagnostic.json
- data/research/e1r/E1R_PHASE3H_MARKET_FLOW_CONFIRMATION_REPORT.md
"""
from __future__ import annotations

import importlib.util
import json
import math
import statistics
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

E1_ID = "E1_AUDITED_G4_MINHOLD10"
E1R_ID = "E1R_REGIME_AWARE_V0_1"

BACKTEST_PATH = Path("exports/backtest.json")
PRICES_DIR = Path("data/prices")
REGIME_PATH = Path("data/research/e1_5y/regimes/spx_regime_daily.json")
PHASE3G_SCRIPT = Path("scripts/e1r_phase3g_smooth_trend_confirmation_diagnostic.py")
PHASE3G_JSON = Path("data/research/e1r/e1r_phase3g_smooth_trend_confirmation_diagnostic.json")

OUT_DIR = Path("data/research/e1r")
OUT_JSON = OUT_DIR / "e1r_phase3h_market_flow_confirmation_diagnostic.json"
OUT_MD = OUT_DIR / "E1R_PHASE3H_MARKET_FLOW_CONFIRMATION_REPORT.md"

HORIZONS = [5, 10, 20, 30]
DEDUP_GAP_DAYS = 5
TARGET_BASE_RULES = ["SIDEWAYS_STC80", "DOWNTREND_STC90"]


def load_phase3g_module():
    if not PHASE3G_SCRIPT.exists():
        raise FileNotFoundError(f"Missing required script: {PHASE3G_SCRIPT}")
    spec = importlib.util.spec_from_file_location("phase3g", PHASE3G_SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import {PHASE3G_SCRIPT}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def load_json(path: Path) -> Any:
    if not path.exists():
        raise FileNotFoundError(f"Missing required input: {path}")
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def pct_str(x: Any) -> str:
    try:
        if x is None:
            return "n/a"
        y = float(x)
        if not math.isfinite(y):
            return "n/a"
        return f"{y:+.2f}%"
    except Exception:
        return "n/a"


def round_or_none(x: Any, nd: int = 3) -> Any:
    try:
        if x is None:
            return None
        y = float(x)
        return round(y, nd) if math.isfinite(y) else None
    except Exception:
        return None


def num(x: Any, default: float = 0.0) -> float:
    try:
        if x is None:
            return default
        y = float(x)
        return y if math.isfinite(y) else default
    except Exception:
        return default


def avg(xs: list[float]) -> float | None:
    vals = [float(x) for x in xs if isinstance(x, (int, float)) and math.isfinite(float(x))]
    return statistics.mean(vals) if vals else None


def safe_variant_results(backtest: dict[str, Any]) -> dict[str, Any]:
    try:
        return backtest["backtest"]["results"]["layer_d"]["variant_results"]
    except KeyError as exc:
        raise KeyError("Cannot locate backtest.results.layer_d.variant_results in exports/backtest.json") from exc


def extract_rows(obj: Any) -> list[dict[str, Any]]:
    if isinstance(obj, list):
        return [r for r in obj if isinstance(r, dict)]
    if isinstance(obj, dict):
        for key in ["data", "series", "history", "prices"]:
            if isinstance(obj.get(key), list):
                return [r for r in obj[key] if isinstance(r, dict)]
        # Date-keyed dict.
        rows = []
        for d, v in obj.items():
            if isinstance(d, str) and len(d) >= 10 and d[4] == "-":
                if isinstance(v, dict):
                    r = dict(v)
                    r.setdefault("date", d[:10])
                    rows.append(r)
                elif isinstance(v, (int, float)):
                    rows.append({"date": d[:10], "close": float(v)})
        if rows:
            rows.sort(key=lambda r: str(r.get("date")))
            return rows
        # Columnar dict fallback.
        dates = obj.get("dates") or obj.get("date") or obj.get("Date")
        closes = obj.get("close") or obj.get("closes") or obj.get("prices") or obj.get("Close") or obj.get("adj_close") or obj.get("Adj Close")
        vols = obj.get("volume") or obj.get("volumes") or obj.get("Volume")
        highs = obj.get("high") or obj.get("High")
        lows = obj.get("low") or obj.get("Low")
        if isinstance(dates, list) and isinstance(closes, list):
            out = []
            for i, d in enumerate(dates):
                if i >= len(closes):
                    break
                r = {"date": str(d)[:10], "close": closes[i]}
                if isinstance(vols, list) and i < len(vols):
                    r["volume"] = vols[i]
                if isinstance(highs, list) and i < len(highs):
                    r["high"] = highs[i]
                if isinstance(lows, list) and i < len(lows):
                    r["low"] = lows[i]
                out.append(r)
            return out
    return []


def get_field(row: dict[str, Any], names: list[str]) -> float | None:
    for name in names:
        if name in row and row[name] is not None:
            try:
                y = float(row[name])
                if math.isfinite(y):
                    return y
            except Exception:
                pass
    return None


def price_file_candidates(symbol: str) -> list[Path]:
    safe = symbol.replace("/", "-")
    return [
        PRICES_DIR / f"{symbol}.json",
        PRICES_DIR / f"{safe}.json",
        PRICES_DIR / f"{symbol.replace('^','')}.json",
        PRICES_DIR / f"{symbol.replace('^','_')}.json",
    ]


def load_records(symbol: str) -> dict[str, list[Any]]:
    for path in price_file_candidates(symbol):
        if not path.exists():
            continue
        try:
            rows = extract_rows(load_json(path))
        except Exception:
            continue
        dates, close, volume, high, low = [], [], [], [], []
        for r in rows:
            d = r.get("date") or r.get("Date")
            c = get_field(r, ["close", "Close", "adj_close", "Adj Close"])
            if d is None or c is None:
                continue
            dates.append(str(d)[:10])
            close.append(c)
            volume.append(get_field(r, ["volume", "Volume", "vol"]))
            high.append(get_field(r, ["high", "High"]))
            low.append(get_field(r, ["low", "Low"]))
        if len(dates) >= 90:
            return {"dates": dates, "close": close, "volume": volume, "high": high, "low": low}
    return {"dates": [], "close": [], "volume": [], "high": [], "low": []}


def load_all_records(symbols: list[str]) -> dict[str, dict[str, list[Any]]]:
    out = {}
    for sym in symbols:
        rec = load_records(sym)
        if rec["dates"]:
            out[sym] = rec
    return out


def pct_return(a: float | None, b: float | None) -> float | None:
    if a is None or b is None or a <= 0 or b <= 0:
        return None
    return (b / a - 1.0) * 100.0


def slice_vals(vals: list[Any], start: int, end: int) -> list[float]:
    out = []
    for v in vals[max(0, start): end]:
        if isinstance(v, (int, float)) and math.isfinite(float(v)):
            out.append(float(v))
    return out


def sum_vals(vals: list[Any]) -> float | None:
    xs = [float(v) for v in vals if isinstance(v, (int, float)) and math.isfinite(float(v))]
    return sum(xs) if xs else None


def returns_std(closes: list[float], start: int, end: int) -> float | None:
    rets = []
    s = max(1, start)
    for i in range(s, end):
        if i < len(closes) and closes[i - 1] > 0 and closes[i] > 0:
            rets.append(closes[i] / closes[i - 1] - 1.0)
    if len(rets) < 3:
        return None
    return statistics.pstdev(rets)


def true_ranges(rec: dict[str, list[Any]], start: int, end: int) -> list[float]:
    closes = rec["close"]
    highs = rec.get("high", [])
    lows = rec.get("low", [])
    out = []
    for i in range(max(1, start), min(end, len(closes))):
        h = highs[i] if i < len(highs) else None
        l = lows[i] if i < len(lows) else None
        pc = closes[i - 1]
        if h is None or l is None or pc is None:
            continue
        try:
            out.append(max(float(h) - float(l), abs(float(h) - float(pc)), abs(float(l) - float(pc))))
        except Exception:
            continue
    return out


def flow_metrics(row: dict[str, Any], records_map: dict[str, dict[str, list[Any]]], spx_rec: dict[str, list[Any]]) -> dict[str, Any]:
    sym = row.get("symbol")
    d = row.get("date")
    rec = records_map.get(sym or "")
    if not rec or not d:
        return {"has_volume_data": False}
    dates = rec["dates"]
    idx = {x: i for i, x in enumerate(dates)}
    i = idx.get(str(d))
    if i is None or i < 60:
        return {"has_volume_data": False}

    closes = rec["close"]
    vols = rec.get("volume", [])
    if not vols or i >= len(vols) or vols[i] is None:
        return {"has_volume_data": False}

    avg_vol_5 = avg(slice_vals(vols, i - 4, i + 1))
    avg_vol_10 = avg(slice_vals(vols, i - 9, i + 1))
    avg_vol_20 = avg(slice_vals(vols, i - 19, i + 1))
    avg_vol_50 = avg(slice_vals(vols, i - 49, i + 1))

    rvol_5_20 = avg_vol_5 / avg_vol_20 if avg_vol_5 and avg_vol_20 and avg_vol_20 > 0 else None
    rvol_10_50 = avg_vol_10 / avg_vol_50 if avg_vol_10 and avg_vol_50 and avg_vol_50 > 0 else None

    def up_volume_ratio(n: int) -> float | None:
        total = 0.0
        up = 0.0
        for k in range(max(1, i - n + 1), i + 1):
            v = vols[k] if k < len(vols) else None
            if not isinstance(v, (int, float)) or not math.isfinite(float(v)):
                continue
            total += float(v)
            if closes[k] > closes[k - 1]:
                up += float(v)
        return up / total * 100.0 if total > 0 else None

    upvol_10 = up_volume_ratio(10)
    upvol_20 = up_volume_ratio(20)

    dollar_vals = []
    for k in range(max(0, i - 19), i + 1):
        if k < len(vols) and vols[k] is not None and closes[k] is not None:
            try:
                dollar_vals.append(float(vols[k]) * float(closes[k]))
            except Exception:
                pass
    dollar_vol_20_m = statistics.mean(dollar_vals) / 1_000_000.0 if dollar_vals else None

    stock_20 = pct_return(closes[i - 20] if i >= 20 else None, closes[i])
    spx_idx = {x: j for j, x in enumerate(spx_rec["dates"])}
    si = spx_idx.get(str(d))
    spx_20 = pct_return(spx_rec["close"][si - 20], spx_rec["close"][si]) if si is not None and si >= 20 else None
    rel_20 = stock_20 - spx_20 if stock_20 is not None and spx_20 is not None else None

    # Setup quality: dry-up and volatility compression are useful before a break/confirmation.
    volume_dryup_5_20 = avg_vol_5 / avg_vol_20 if avg_vol_5 and avg_vol_20 and avg_vol_20 > 0 else None
    trs5 = true_ranges(rec, i - 4, i + 1)
    trs20 = true_ranges(rec, i - 19, i + 1)
    atr_comp = None
    if trs5 and trs20 and statistics.mean(trs20) > 0:
        atr_comp = statistics.mean(trs5) / statistics.mean(trs20)
    else:
        std5 = returns_std(closes, i - 4, i + 1)
        std20 = returns_std(closes, i - 19, i + 1)
        if std5 is not None and std20 and std20 > 0:
            atr_comp = std5 / std20

    hi252 = max(closes[max(0, i - 251): i + 1]) if i >= 20 else None
    dist_52w_high_pct = (closes[i] / hi252 - 1.0) * 100.0 if hi252 and hi252 > 0 else None

    # 100-point market-flow score. Research prior only.
    score = 0.0
    # Relative volume / participation, 25 pts.
    score += min(15.0, max(0.0, (num(rvol_5_20) - 0.9) / 0.5 * 15.0))
    score += min(10.0, max(0.0, (num(rvol_10_50) - 0.9) / 0.4 * 10.0))
    # Up-day volume confirmation, 25 pts.
    score += min(13.0, max(0.0, (num(upvol_10) - 45.0) / 20.0 * 13.0))
    score += min(12.0, max(0.0, (num(upvol_20) - 45.0) / 20.0 * 12.0))
    # Liquidity / real money participation, 15 pts.
    adv = num(dollar_vol_20_m)
    if adv >= 500:
        score += 15.0
    elif adv >= 250:
        score += 12.0
    elif adv >= 100:
        score += 9.0
    elif adv >= 50:
        score += 5.0
    # Price-volume confirmation, 15 pts.
    if stock_20 is not None and stock_20 > 0:
        score += 5.0
    if rel_20 is not None and rel_20 > 0:
        score += 5.0
    if upvol_10 is not None and upvol_10 >= 55:
        score += 5.0
    # Setup quality, 20 pts: dry-up before expansion, volatility compression, high proximity.
    if volume_dryup_5_20 is not None:
        score += min(7.0, max(0.0, (1.05 - volume_dryup_5_20) / 0.35 * 7.0))
    if atr_comp is not None:
        score += min(7.0, max(0.0, (1.05 - atr_comp) / 0.35 * 7.0))
    if dist_52w_high_pct is not None:
        score += min(6.0, max(0.0, (20.0 + dist_52w_high_pct) / 20.0 * 6.0))  # full near high, zero if >20% below high

    out = {
        "has_volume_data": True,
        "avg_volume_5d": round_or_none(avg_vol_5, 3),
        "avg_volume_20d": round_or_none(avg_vol_20, 3),
        "avg_volume_50d": round_or_none(avg_vol_50, 3),
        "rvol_5_20": round_or_none(rvol_5_20, 4),
        "rvol_10_50": round_or_none(rvol_10_50, 4),
        "up_volume_ratio_10d_pct": round_or_none(upvol_10, 3),
        "up_volume_ratio_20d_pct": round_or_none(upvol_20, 3),
        "avg_dollar_volume_20d_m": round_or_none(dollar_vol_20_m, 3),
        "stock_return_20d_pct": round_or_none(stock_20, 3),
        "spx_return_20d_pct": round_or_none(spx_20, 3),
        "relative_return_20d_vs_spx_pct": round_or_none(rel_20, 3),
        "volume_dryup_5_20": round_or_none(volume_dryup_5_20, 4),
        "volatility_compression_5_20": round_or_none(atr_comp, 4),
        "distance_to_52w_high_pct": round_or_none(dist_52w_high_pct, 3),
        "market_flow_score": round(score, 3),
        "flow_flags": {
            "relative_volume_confirmed": bool((rvol_5_20 is not None and rvol_5_20 >= 1.2) or (rvol_10_50 is not None and rvol_10_50 >= 1.1)),
            "up_volume_confirmed": bool((upvol_10 is not None and upvol_10 >= 55) and (upvol_20 is not None and upvol_20 >= 52)),
            "liquid_100m_confirmed": bool(dollar_vol_20_m is not None and dollar_vol_20_m >= 100),
            "price_volume_confirmed": bool(stock_20 is not None and stock_20 > 0 and rel_20 is not None and rel_20 > 0 and upvol_10 is not None and upvol_10 >= 55),
            "setup_compression_confirmed": bool((volume_dryup_5_20 is not None and volume_dryup_5_20 <= 0.85) or (atr_comp is not None and atr_comp <= 0.85)),
            "near_52w_high_confirmed": bool(dist_52w_high_pct is not None and dist_52w_high_pct >= -15),
        },
    }
    return out


def attach_flow(rows: list[dict[str, Any]], records_map: dict[str, dict[str, list[Any]]], spx_rec: dict[str, list[Any]]) -> list[dict[str, Any]]:
    out = []
    for r in rows:
        m = flow_metrics(r, records_map, spx_rec)
        rr = dict(r)
        rr.update(m)
        out.append(rr)
    return out


def pass_flow_rule(row: dict[str, Any], rule: str) -> bool:
    flags = row.get("flow_flags") or {}
    if not row.get("has_volume_data"):
        return False
    if rule == "STC_ONLY_WITH_VOLUME_DATA":
        return True
    if rule == "STC_PLUS_RELATIVE_VOLUME":
        return bool(flags.get("relative_volume_confirmed"))
    if rule == "STC_PLUS_UP_VOLUME":
        return bool(flags.get("up_volume_confirmed"))
    if rule == "STC_PLUS_DOLLAR_VOLUME_100M":
        return bool(flags.get("liquid_100m_confirmed"))
    if rule == "STC_PLUS_RVOL_AND_UPVOL":
        return bool(flags.get("relative_volume_confirmed") and flags.get("up_volume_confirmed"))
    if rule == "STC_PLUS_PRICE_VOLUME":
        return bool(flags.get("price_volume_confirmed"))
    if rule == "STC_PLUS_FLOW_SCORE_60":
        return num(row.get("market_flow_score")) >= 60
    if rule == "STC_PLUS_FLOW_SCORE_70":
        return num(row.get("market_flow_score")) >= 70
    if rule == "STC_PLUS_FLOW_SCORE_60_AND_LIQUID":
        return num(row.get("market_flow_score")) >= 60 and bool(flags.get("liquid_100m_confirmed"))
    return False


def top1_by_date_flow(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_date: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        by_date[r["date"]].append(r)
    out = []
    for d, group in sorted(by_date.items()):
        out.append(sorted(
            group,
            # Keep Phase 3H baseline comparable with Phase 3G STC screen:
            # select daily Top1 by STC quality first; market-flow is used as a filter/tie-breaker,
            # not as the primary ranking key in this diagnostic.
            key=lambda x: (-num(x.get("stc_score")), int(x.get("leader_rank") or 9999), -num(x.get("leader_score")), -num(x.get("market_flow_score")), str(x.get("symbol") or "")),
        )[0])
    return out


def summarize_rule(rule_rows: list[dict[str, Any]], phase3g, price_map: dict[str, tuple[list[str], list[float]]], spx_dates: list[str], spx_closes: list[float]) -> dict[str, Any]:
    daily_top1 = top1_by_date_flow(rule_rows)
    enriched_all = phase3g.enrich_forward(rule_rows, price_map, spx_dates, spx_closes)
    enriched_top1 = phase3g.enrich_forward(daily_top1, price_map, spx_dates, spx_closes)
    dedup_all = phase3g.dedup_by_symbol_gap(enriched_all, spx_dates, DEDUP_GAP_DAYS)
    dedup_top1 = phase3g.dedup_by_symbol_gap(enriched_top1, spx_dates, DEDUP_GAP_DAYS)
    return {
        "raw_candidates": len(rule_rows),
        "candidate_days": len({r.get("date") for r in rule_rows}),
        "daily_top1_count": len(daily_top1),
        "dedup_all_count": len(dedup_all),
        "dedup_top1_count": len(dedup_top1),
        "forward_all_dedup": phase3g.summarize_forward(dedup_all),
        "forward_daily_top1_dedup": phase3g.summarize_forward(dedup_top1),
        "concentration_top1_dedup": phase3g.concentration(dedup_top1),
        "avg_market_flow_score_top1": round_or_none(avg([num(r.get("market_flow_score")) for r in dedup_top1]), 3),
        "sample_top1": dedup_top1[:10],
    }


def base_stc_candidates(phase3g, builder, spx_dates: list[str], regime_daily: dict[str, Any]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    by_rule, diag = phase3g.screen_stc_candidates(builder, spx_dates, regime_daily)
    rows = []
    for rule in TARGET_BASE_RULES:
        for r in by_rule.get(rule, []):
            rr = dict(r)
            rr["base_stc_rule"] = rule
            rows.append(rr)
    return rows, diag


def decision_from_flow(rule_results: dict[str, Any]) -> dict[str, Any]:
    base = rule_results.get("STC_ONLY_WITH_VOLUME_DATA", {}).get("forward_daily_top1_dedup", {})
    base20 = (base.get("20d") or {}).get("avg_excess_pct")
    base30 = (base.get("30d") or {}).get("avg_excess_pct")
    best_rule = None
    best_score = -999.0
    for rule, rr in rule_results.items():
        if rule == "STC_ONLY_WITH_VOLUME_DATA":
            continue
        f20 = rr.get("forward_daily_top1_dedup", {}).get("20d", {})
        f30 = rr.get("forward_daily_top1_dedup", {}).get("30d", {})
        n = f20.get("n") or 0
        ex20 = f20.get("avg_excess_pct")
        ex30 = f30.get("avg_excess_pct")
        wr20 = f20.get("excess_win_rate_pct") or 0
        if n >= 10 and ex20 is not None and ex30 is not None:
            score = ex20 + ex30 + max(0, wr20 - 50) / 10
            if score > best_score:
                best_score = score
                best_rule = rule
    if best_rule:
        rr = rule_results[best_rule]
        f20 = rr["forward_daily_top1_dedup"]["20d"]
        f30 = rr["forward_daily_top1_dedup"]["30d"]
        n = f20.get("n") or 0
        ex20 = f20.get("avg_excess_pct")
        ex30 = f30.get("avg_excess_pct")
        wr20 = f20.get("excess_win_rate_pct") or 0
        improved = (base20 is None or (ex20 is not None and ex20 > base20)) and (base30 is None or (ex30 is not None and ex30 > base30))
        if n >= 20 and ex20 is not None and ex30 is not None and ex20 > 0 and ex30 > 0 and wr20 >= 50 and improved:
            return {
                "decision": "MARKET_FLOW_CONFIRMATION_PROMISING_DIAGNOSTIC_ONLY",
                "best_rule": best_rule,
                "reason": "Flow confirmation produced positive 20D/30D excess, adequate sample, and improvement over STC-only. Still diagnostic only; execution requires separate portfolio simulation.",
            }
        if n >= 10 and improved and ex20 is not None and ex20 > 0:
            return {
                "decision": "MARKET_FLOW_CONFIRMATION_OBSERVATIONAL_ONLY",
                "best_rule": best_rule,
                "reason": "Flow confirmation improved some metrics but does not meet full execution-evidence thresholds.",
            }
    return {
        "decision": "MARKET_FLOW_WATCHLIST_ONLY_FOR_NOW",
        "best_rule": best_rule,
        "reason": "Market-flow filters did not provide sufficient positive 20D/30D excess evidence versus SPX. Keep SIDEWAYS/DOWNTREND candidates as Watchlist/radar only.",
    }


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    phase3g = load_phase3g_module()

    bj = load_json(BACKTEST_PATH)
    variants = safe_variant_results(bj)
    if E1_ID not in variants or E1R_ID not in variants:
        print("Missing required E1/E1-R variants in exports/backtest.json.")
        print(f"Found: {list(variants.keys())}")
        print("Run `python3 run_backtest.py` first, then rerun this diagnostic.")
        raise SystemExit(2)

    spx_dates, spx_closes = phase3g.load_price_series("^GSPC")
    if not spx_dates:
        spx_dates, spx_closes = phase3g.load_price_series("GSPC")
    if not spx_dates:
        raise SystemExit("SPX price series not found under data/prices.")
    spx_rec = load_records("^GSPC") or load_records("GSPC")
    if not spx_rec.get("dates"):
        spx_rec = {"dates": spx_dates, "close": spx_closes, "volume": [], "high": [], "low": []}

    regime_daily = phase3g.load_regime_daily()
    price_map = phase3g.load_all_price_series()
    builder = phase3g.DailySignalBuilder(price_map)

    base_rows, stc_diag = base_stc_candidates(phase3g, builder, spx_dates, regime_daily)
    base_symbols = sorted({r.get("symbol") for r in base_rows if r.get("symbol")})
    records_map = load_all_records(base_symbols)
    flow_rows = attach_flow(base_rows, records_map, spx_rec)

    rules = [
        "STC_ONLY_WITH_VOLUME_DATA",
        "STC_PLUS_RELATIVE_VOLUME",
        "STC_PLUS_UP_VOLUME",
        "STC_PLUS_DOLLAR_VOLUME_100M",
        "STC_PLUS_RVOL_AND_UPVOL",
        "STC_PLUS_PRICE_VOLUME",
        "STC_PLUS_FLOW_SCORE_60",
        "STC_PLUS_FLOW_SCORE_70",
        "STC_PLUS_FLOW_SCORE_60_AND_LIQUID",
    ]
    rule_results = {}
    for rule in rules:
        rows = [r for r in flow_rows if pass_flow_rule(r, rule)]
        rule_results[rule] = summarize_rule(rows, phase3g, price_map, spx_dates, spx_closes)

    # By-regime view for the most important rules.
    by_regime = {}
    for regime in ["SIDEWAYS", "DOWNTREND"]:
        by_regime[regime] = {}
        for rule in ["STC_ONLY_WITH_VOLUME_DATA", "STC_PLUS_FLOW_SCORE_60", "STC_PLUS_FLOW_SCORE_70", "STC_PLUS_RVOL_AND_UPVOL"]:
            rows = [r for r in flow_rows if r.get("spx_regime") == regime and pass_flow_rule(r, rule)]
            by_regime[regime][rule] = summarize_rule(rows, phase3g, price_map, spx_dates, spx_closes)

    flow_score_values = [num(r.get("market_flow_score")) for r in flow_rows if r.get("has_volume_data")]
    decision = decision_from_flow(rule_results)

    e1 = variants[E1_ID]
    e1r = variants[E1R_ID]
    result = {
        "status": "DIAGNOSTIC_ONLY_NO_TRADING_LOGIC_CHANGE",
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "strategy_id": E1R_ID,
        "inputs": {
            "backtest": str(BACKTEST_PATH),
            "prices_dir": str(PRICES_DIR),
            "regime_source": str(REGIME_PATH),
            "phase3g_script": str(PHASE3G_SCRIPT),
            "phase3g_json": str(PHASE3G_JSON),
        },
        "fairness_controls": {
            "does_not_change_trading_logic": True,
            "protects_existing_uptrend_confirmed_execution": True,
            "evaluates_only_sideways_downtrend_stc_candidates": True,
            "uses_same_stc_logic_as_phase3g": True,
            "forward_return_starts_on_signal_date": True,
        },
        "portfolio_context": {
            "E1": {
                "total_return_pct": e1.get("total_return_pct"),
                "max_drawdown_pct": e1.get("max_drawdown_pct"),
                "profit_factor": e1.get("profit_factor"),
                "number_of_trades": e1.get("number_of_trades"),
            },
            "E1R": {
                "total_return_pct": e1r.get("total_return_pct"),
                "max_drawdown_pct": e1r.get("max_drawdown_pct"),
                "profit_factor": e1r.get("profit_factor"),
                "number_of_trades": e1r.get("number_of_trades"),
            },
        },
        "market_flow_definition_v0_1": {
            "score_max": 100,
            "components": {
                "relative_volume_participation": 25,
                "up_day_volume_confirmation": 25,
                "dollar_volume_liquidity": 15,
                "price_volume_confirmation": 15,
                "setup_quality_dryup_compression_52w_proximity": 20,
            },
            "note": "Research prior only. Not a frozen trading rule.",
        },
        "candidate_universe": {
            "base_stc_candidates": len(base_rows),
            "symbols_with_price_records": len(records_map),
            "candidates_with_volume_data": sum(1 for r in flow_rows if r.get("has_volume_data")),
            "regime_day_counts": stc_diag.get("regime_day_counts"),
            "flow_score_summary": {
                "n": len(flow_score_values),
                "avg": round_or_none(avg(flow_score_values), 3),
                "median": round_or_none(statistics.median(flow_score_values), 3) if flow_score_values else None,
                "max": round_or_none(max(flow_score_values), 3) if flow_score_values else None,
                "min": round_or_none(min(flow_score_values), 3) if flow_score_values else None,
            },
        },
        "rule_results": rule_results,
        "by_regime_results": by_regime,
        "decision": decision,
        "interpretation": {
            "primary_question": "Does market-flow confirmation improve SIDEWAYS/DOWNTREND STC candidates enough for future execution research?",
            "uptrend_policy": "No UPTREND logic is changed or evaluated for execution changes in this phase.",
            "next_step_if_promising": "Run separate capital-aware portfolio simulation before any execution-layer change.",
        },
    }

    OUT_JSON.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")

    md = []
    md.append("# E1-R Phase 3H Market Flow Confirmation Diagnostic")
    md.append("")
    md.append(f"Generated: `{result['generated_at']}`")
    md.append("")
    md.append("Status: **DIAGNOSTIC_ONLY_NO_TRADING_LOGIC_CHANGE**")
    md.append("")
    md.append("## 1. Question")
    md.append("")
    md.append("For SIDEWAYS / DOWNTREND smooth-trend candidates, does market trading money confirmation improve 20D / 30D excess return versus SPX?")
    md.append("")
    md.append("This phase does not touch the existing UPTREND Confirmed execution path.")
    md.append("")
    md.append("## 2. Market Flow Score v0.1")
    md.append("")
    md.append("| Component | Weight |")
    md.append("|---|---:|")
    for k, v in result["market_flow_definition_v0_1"]["components"].items():
        md.append(f"| {k} | {v} |")
    md.append("")
    md.append("## 3. Rule Results")
    md.append("")
    md.append("| Rule | Raw | Days | Dedup Top1 | 20D Avg | 20D Excess | 20D Excess WR | 30D Avg | 30D Excess | 30D Excess WR |")
    md.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for rule in rules:
        rr = rule_results[rule]
        f20 = rr["forward_daily_top1_dedup"]["20d"]
        f30 = rr["forward_daily_top1_dedup"]["30d"]
        md.append(
            f"| {rule} | {rr['raw_candidates']} | {rr['candidate_days']} | {rr['dedup_top1_count']} | "
            f"{pct_str(f20.get('avg_return_pct'))} | {pct_str(f20.get('avg_excess_pct'))} | {f20.get('excess_win_rate_pct')}% | "
            f"{pct_str(f30.get('avg_return_pct'))} | {pct_str(f30.get('avg_excess_pct'))} | {f30.get('excess_win_rate_pct')}% |"
        )
    md.append("")
    md.append("## 4. By-Regime Check")
    md.append("")
    md.append("| Regime | Rule | Dedup Top1 | 20D Excess | 30D Excess |")
    md.append("|---|---|---:|---:|---:|")
    for regime, rows in by_regime.items():
        for rule, rr in rows.items():
            f20 = rr["forward_daily_top1_dedup"]["20d"]
            f30 = rr["forward_daily_top1_dedup"]["30d"]
            md.append(f"| {regime} | {rule} | {rr['dedup_top1_count']} | {pct_str(f20.get('avg_excess_pct'))} | {pct_str(f30.get('avg_excess_pct'))} |")
    md.append("")
    md.append("## 5. Decision")
    md.append("")
    md.append(f"Decision: **{decision['decision']}**")
    md.append("")
    md.append(f"Best rule: `{decision.get('best_rule')}`")
    md.append("")
    md.append(f"Reason: {decision['reason']}")
    md.append("")
    md.append("## 6. Frozen Interpretation")
    md.append("")
    md.append("Market-flow confirmation is evaluated only as a non-UPTREND diagnostic overlay. It must not be applied to UPTREND Confirmed execution without a separate Phase 4 comparison that proves it protects the current UPTREND edge.")
    md.append("")
    OUT_MD.write_text("\n".join(md), encoding="utf-8")

    print("E1-R PHASE 3H MARKET FLOW CONFIRMATION DIAGNOSTIC")
    print("Status: DIAGNOSTIC_ONLY_NO_TRADING_LOGIC_CHANGE")
    print(f"Base STC candidates: {len(base_rows)}")
    print(f"Candidates with volume data: {sum(1 for r in flow_rows if r.get('has_volume_data'))}")
    print(f"Regime day counts: {stc_diag.get('regime_day_counts')}")
    print("\nMarket-flow rule results:")
    for rule in rules:
        rr = rule_results[rule]
        f20 = rr["forward_daily_top1_dedup"]["20d"]
        f30 = rr["forward_daily_top1_dedup"]["30d"]
        print(
            f"  {rule}: raw={rr['raw_candidates']} days={rr['candidate_days']} dedup_top1={rr['dedup_top1_count']} "
            f"20D avg={pct_str(f20.get('avg_return_pct'))} excess={pct_str(f20.get('avg_excess_pct'))} excessWR={f20.get('excess_win_rate_pct')}% "
            f"30D avg={pct_str(f30.get('avg_return_pct'))} excess={pct_str(f30.get('avg_excess_pct'))}"
        )
    print(f"\nDecision: {decision['decision']}")
    print(f"Best rule: {decision.get('best_rule')}")
    print(f"Reason: {decision['reason']}")
    print(f"Output: {OUT_JSON}")
    print(f"Report: {OUT_MD}")


if __name__ == "__main__":
    main()
