"""Smoke tests for standalone E1R market gate evaluator.

Generated by K2-R12. This file intentionally tests only the standalone
MarketGateEvaluator contract; it does not import or execute legacy backtest code.
"""

from e1r_engine.market_gate import MarketGateConfig, MarketGateEvaluator, MarketGateInputs


def test_market_gate_invalid_direct_formula_guard() -> None:
    cfg = MarketGateConfig()
    inputs = MarketGateInputs(
        date="2021-06-18",
        spx_close=4166.45,
        spx_ma50=4181.59,
        spx_day_return=-0.013124,
        market_state="CAUTIOUS_ON",
        entry_capacity=2,
    )

    decision = MarketGateEvaluator.evaluate(cfg, inputs)

    assert decision.gate_state == "ALLOW"
    assert decision.market_entry_allowed is True
    assert decision.market_shock is False
    assert decision.market_risk_off is False


def test_market_gate_shock_precedence():
    from e1r_engine.market_state import (
        MarketStateConfig,
        MarketStateEvaluator,
        MarketStateInputs,
    )
    from e1r_engine.market_gate import (
        MarketGateConfig,
        MarketGateEvaluator,
        MarketGateInputs,
    )
    state = MarketStateEvaluator.evaluate(
        MarketStateConfig(
            market_shock_gate_enabled=True,
            market_shock_daily_return=-0.02,
        ),
        MarketStateInputs(
            date="2021-05-12",
            spx_close=110.0,
            spx_ma50=100.0,
            spx_ma50_10d_ago=99.0,
            spx_day_return=-0.02,
            ndx_close=110.0,
            ndx_ma50=100.0,
            sox_close=110.0,
            sox_ma50=100.0,
            max_positions=3,
        ),
    )
    gate = MarketGateEvaluator.evaluate(
        MarketGateConfig(
            variant="D3_RISK_OFF_PLUS_SHOCK_GATE",
            market_gate_enabled=True,
            risk_off_below_spx_ma50=True,
            market_shock_gate_enabled=True,
            market_shock_daily_return=-0.02,
        ),
        MarketGateInputs(
            date=state.date,
            spx_close=state.spx_close,
            spx_ma50=state.spx_ma50,
            spx_day_return=state.spx_day_return,
            market_state=state.market_state,
            entry_capacity=state.entry_capacity,
            existing_positions_count=0,
        ),
    )
    assert state.shock_active is True
    assert state.market_state == "CASH_MODE"
    assert state.entry_capacity == 0
    assert gate.market_shock is True
    assert gate.gate_state == "SHOCK"
