"""Smoke tests for standalone E1R market gate evaluator.

Generated by K2-R12. This file intentionally tests only the standalone
MarketGateEvaluator contract; it does not import or execute legacy backtest code.
"""

from e1r_engine.market_gate import MarketGateConfig, MarketGateEvaluator, MarketGateInputs


def test_market_gate_invalid_direct_formula_guard() -> None:
    cfg = MarketGateConfig()
    inputs = MarketGateInputs(
        date="2021-06-18",
        spx_close=4166.45,
        spx_ma50=4181.59,
        spx_day_return=-0.013124,
        market_state="CAUTIOUS_ON",
        entry_capacity=2,
    )

    decision = MarketGateEvaluator.evaluate(cfg, inputs)

    assert decision.gate_state == "ALLOW"
    assert decision.market_entry_allowed is True
    assert decision.market_shock is False
    assert decision.market_risk_off is False


def test_market_gate_shock_precedence() -> None:
    cfg = MarketGateConfig()
    inputs = MarketGateInputs(
        date="2021-05-12",
        spx_day_return=-0.021449,
        market_state="CASH_MODE",
        entry_capacity=0,
    )

    decision = MarketGateEvaluator.evaluate(cfg, inputs)

    assert decision.gate_state == "SHOCK"
    assert decision.market_entry_allowed is False
    assert decision.market_shock is True
    assert decision.market_risk_off is False
